// type: 'static' rounds come from fantasyDeadlines.js (hand-maintained).
// type: 'dynamic' rounds are fetched live via src/api/fantasyFixtures.js.
// emoji is the fallback shown if logoUrl fails to load (see FantasyLeagueIcon).
export const FANTASY_LEAGUES = [
  {
    id: 'eliteserien',
    name: 'Eliteserien Fantasy',
    emoji: '🇳🇴',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/50/Eliteserien_logo.svg',
    type: 'static',
    accentColor: '#6366f1',
    accentClass: 'bg-indigo-600',
    borderClass: 'border-l-indigo-500',
    textClass: 'text-indigo-400',
    badgeClass: 'bg-indigo-500/20 text-indigo-400 border border-indigo-500/30',
    iconBg: 'bg-white',
  },
  {
    id: 'allsvenskan',
    name: 'Allsvenskan Fantasy',
    emoji: '🇸🇪',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4a/Allsvenskan_logo.svg',
    type: 'static',
    accentColor: '#eab308',
    accentClass: 'bg-yellow-600',
    borderClass: 'border-l-yellow-500',
    textClass: 'text-yellow-400',
    badgeClass: 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30',
    iconBg: 'bg-white',
  },
  {
    id: 'premierLeague',
    name: 'Premier League Fantasy',
    emoji: '🇬🇧',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f2/Premier_League_Logo.svg',
    type: 'static',
    accentColor: '#8b5cf6',
    accentClass: 'bg-violet-600',
    borderClass: 'border-l-violet-500',
    textClass: 'text-violet-400',
    badgeClass: 'bg-violet-500/20 text-violet-400 border border-violet-500/30',
    iconBg: 'bg-white',
  },
  {
    id: 'bundesliga',
    name: 'Bundesliga Fantasy',
    emoji: '🇩🇪',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/d/df/Bundesliga_logo_%282017%29.svg',
    type: 'dynamic',
    accentColor: '#f97316',
    accentClass: 'bg-orange-600',
    borderClass: 'border-l-orange-500',
    textClass: 'text-orange-400',
    badgeClass: 'bg-orange-500/20 text-orange-400 border border-orange-500/30',
    iconBg: 'bg-white',
  },
  {
    id: 'serieA',
    name: 'Serie A Fantasy',
    emoji: '🇮🇹',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/ab/Serie_A_ENILIVE_logo.svg',
    type: 'dynamic',
    accentColor: '#14b8a6',
    accentClass: 'bg-teal-600',
    borderClass: 'border-l-teal-500',
    textClass: 'text-teal-400',
    badgeClass: 'bg-teal-500/20 text-teal-400 border border-teal-500/30',
    iconBg: 'bg-white',
  },
  {
    id: 'championsLeague',
    name: 'Champions League Fantasy',
    emoji: '⭐',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f5/UEFA_Champions_League.svg',
    type: 'static',
    accentColor: '#3b82f6',
    accentClass: 'bg-blue-600',
    borderClass: 'border-l-blue-500',
    textClass: 'text-blue-400',
    badgeClass: 'bg-blue-500/20 text-blue-400 border border-blue-500/30',
    iconBg: 'bg-white',
  },
]

export const FANTASY_LEAGUE_MAP = Object.fromEntries(FANTASY_LEAGUES.map(l => [l.id, l]))
