export const LEAGUES = [
  {
    id: 'mlb',
    name: 'MLB',
    emoji: '⚾',
    logoUrl: 'https://www.mlbstatic.com/team-logos/119.svg',
    primaryTeamId: '119',
    description: 'LA Dodgers + All Playoffs',
    accentColor: '#3b82f6',
    accentClass: 'bg-blue-600',
    borderClass: 'border-l-blue-500',
    textClass: 'text-blue-400',
    badgeClass: 'bg-blue-500/20 text-blue-400 border border-blue-500/30',
    iconBg: 'bg-blue-950/60',
  },
  {
    id: 'nba',
    name: 'NBA',
    emoji: '🏀',
    logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
    primaryTeamId: '13',
    description: 'LA Lakers + All Playoffs',
    accentColor: '#a855f7',
    accentClass: 'bg-purple-600',
    borderClass: 'border-l-purple-500',
    textClass: 'text-purple-400',
    badgeClass: 'bg-purple-500/20 text-purple-400 border border-purple-500/30',
    iconBg: 'bg-purple-950/60',
  },
  {
    id: 'nfl',
    name: 'NFL',
    emoji: '🏈',
    logoUrl: 'https://a.espncdn.com/i/teamlogos/leagues/500/nfl.png',
    primaryTeamId: null,
    description: 'All Games + All Playoffs',
    accentColor: '#10b981',
    accentClass: 'bg-emerald-600',
    borderClass: 'border-l-emerald-500',
    textClass: 'text-emerald-400',
    badgeClass: 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30',
    iconBg: 'bg-emerald-950/60',
  },
  {
    id: 'bbl',
    name: 'BBL',
    emoji: '🏏',
    logoUrl: null,
    primaryTeamId: null,
    description: 'All Games + All Playoffs',
    accentColor: '#f59e0b',
    accentClass: 'bg-amber-600',
    borderClass: 'border-l-amber-500',
    textClass: 'text-amber-400',
    badgeClass: 'bg-amber-500/20 text-amber-400 border border-amber-500/30',
    iconBg: 'bg-amber-950/60',
  },
  {
    id: 'mls',
    name: 'MLS',
    emoji: '⚽',
    logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/20232.png',
    primaryTeamId: '20232',
    description: 'Inter Miami CF · All Competitions',
    accentColor: '#ec4899',
    accentClass: 'bg-pink-600',
    borderClass: 'border-l-pink-500',
    textClass: 'text-pink-400',
    badgeClass: 'bg-pink-500/20 text-pink-400 border border-pink-500/30',
    iconBg: 'bg-pink-950/60',
  },
  {
    id: 'epl',
    name: 'EPL',
    emoji: '🔴',
    logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/360.png',
    primaryTeamId: '360',
    description: 'Man United · All Competitions',
    accentColor: '#ef4444',
    accentClass: 'bg-red-600',
    borderClass: 'border-l-red-500',
    textClass: 'text-red-400',
    badgeClass: 'bg-red-500/20 text-red-400 border border-red-500/30',
    iconBg: 'bg-red-950/60',
  },
]

export const LEAGUE_MAP = Object.fromEntries(LEAGUES.map(l => [l.id, l]))
